apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mongodb
  template:
    metadata:
      labels:
        app: restaurant-mongodb
    spec:
      containers:
        - name: restaurant-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: restaurant_db
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-mongodb
spec:
  type: ClusterIP
  selector:
    app: restaurant-mongodb
  ports:
    - port: 27017
      targetPort: 27017