apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-schema-registry
  template:
    metadata:
      labels:
        app: restaurant-schema-registry
    spec:
      containers:
        - name: restaurant-schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "restaurant-schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "restaurant-kafka-broker:29092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-schema-registry
spec:
  type: ClusterIP
  selector:
    app: restaurant-schema-registry
  ports:
    - port: 8081
      targetPort: 8081