apiVersion: v1
kind: Service
metadata:
  name: restaurant-schema-registry
spec:
  type: ClusterIP
  selector:
    app: restaurant-schema-registry
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-kafka-ui
  template:
    metadata:
      labels:
        app: restaurant-kafka-ui
    spec:
      containers:
        - name: restaurant-kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_NAME
              value: "restaurant"
            - name: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
              value: "restaurant-kafka-broker:29092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-kafka-ui
spec:
  type: ClusterIP
  selector:
    app: restaurant-kafka-ui
  ports:
    - port: 8080
      targetPort: 8080