ALTER TABLE `users`
ADD COLUMN `is_disabled` BOOLEAN DEFAULT FALSE,
ADD COLUMN `is_deleted` BOOLEAN DEFAULT FALSE,
ADD COLUMN `is_verified` BOOLEAN DEFAULT FALSE,
ADD COLUMN `identification_number` VARCHAR(255) DEFAULT '',
ADD COLUMN `vehicle_number` VARCHAR(255) DEFAULT '';