apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-frontend
  labels:
    app: food-delivery-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery-frontend
  template:
    metadata:
      labels:
        app: food-delivery-frontend
    spec:
      containers:
        - name: food-delivery-frontend
          image: asirijayawardena920/new-food-delivery-frontend
          imagePullPolicy: Always
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "5173"
          ports:
            - containerPort: 5173
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"