apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-kafka-broker
  template:
    metadata:
      labels:
        app: user-kafka-broker
    spec:
      containers:
        - name: user-kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "user-zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://user-kafka-broker:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: user-kafka-broker
spec:
  type: ClusterIP
  selector:
    app: user-kafka-broker
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092