apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-kafka-ui
  labels:
    app: user-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-kafka-ui
  template:
    metadata:
      labels:
        app: user-kafka-ui
    spec:
      containers:
        - name: user-kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_NAME
              value: "user"
            - name: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
              value: "user-broker:29092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: user-kafka-ui
  labels:
    app: user-kafka-ui
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-kafka-ui